defaults:
  logging_level_default: 5

subarrays:  # 2 subarrays, no defaults overridden
  "1": {}
    # enabled: false  # for example
  "2": {}
    # logging_level_default: 4  # for example

subarraybeams:  # 6 subarraybeams, no defaults overridden
  "1": {}
    # enabled: false  # for example
  "2": {}
    # logging_level_default: 4  # for example
  "3": {}
  "4": {}
  "5": {}
  "6": {}

# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
helm_values:
  # Null ParentTRL given by platform spec, currently the only place to do this.
  ska-tango-devices:
    devices:
      SpsStation:
        low-mccs/spsstation/stfc-ral-4:
          ParentTRL: ""
      MccsTile:
        low-mccs/tile/stfc-ral-2-tpm25:
          BiosVersion: 0.6.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm26:
          BiosVersion: 0.6.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm27:
          BiosVersion: 0.6.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm28:
          BiosVersion: 0.6.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm29:
          BiosVersion: 0.5.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm30:
          BiosVersion: 0.5.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm31:
          BiosVersion: 0.5.0
          PreAduFitted: [true, true]
        low-mccs/tile/stfc-ral-4-tpm32:
          BiosVersion: 0.5.0
          PreAduFitted: [true, true]
    # deviceServerTypes:
    #   spshw:
    #     image:
    #       registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-spshw #localhost:5000
    #       tag: 10.2.0-dev.c4bbc06f3
    #       pullPolicy: Always

  # ska-low-mccs-daq:
  #     ska-tango-devices:
  #       deviceServerTypes:
  #         daq:
  #           image:
  #             registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-daq
  #             tag: 4.3.1-dev.c0aa76e8a
